### ISSUE TITLE
sublime 3 on windows 7: unable to preview on browser

### ISSUE THREAD

**Issue by realtebo** [revolunet/sublimetext-markdown-preview#171]
I installed you package from Package Manager

I try to use cmd+shift+p [as win_key+shift+p] but it open the monitor extender choose in my HP windows 7 machine. 

So I try to change using key bindings.

I tried this [entire content of default key binding config file]:

```
[
{ "keys": ["ctrl+alt+m"], 
  "command": "markdown_preview", 
  "args": {"target": "browser", "parser":"markdown"} 
},
]
```

But when I pressctrl+alt+m, I got converted html into sublime and not the browser preview.

**Comment by jdhao** [comment]
I am using Windows 8.1 and I encountered exactly the same issue as @realtebo. When I press `Shift + Ctrl + M`, the rendered html is not  opened in browser, but in the sublime text tab. It turns out the I have set up the default app to open html file to be sublime text. After change the default app to my Chrome browser. Everything is fine.
