### ISSUE TITLE
anchor not working in Github flavored markdown

### ISSUE THREAD

**Issue by i3zhe** [revolunet/sublimetext-markdown-preview#208]
- [Preparation](#preparation)
- [Authentication](#authentication)
### Preparation

BlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlah
### Authentication

BlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlahBlah

In standard markdown, Authentication is parsed as: 
`<h3 id="authentication">Authentication</h3>` 
and the anchor works well. 

while in Github flavored markdown, it's parsed as: 

```
<h3>
<a name="user-content-authentication" class="anchor" href="#authentication" aria-hidden="true"><span class="octicon octicon-link"></span></a>Authentication</h3>
```

but it doesn't work either with previewing in browser or exporting to html, event I see the `href="#authentication"`. It works when adding id to the h3 `<h3 id="authentication">`.

Not sure if it's my own problem, could anyone help to confirm this please?

**Comment by adam-clarey** [comment]
Hi, has this been made live?

I'm pulling a readme via the api and it works fine except the anchor links don't work.

I'm still scratching my head as to why the anchor links do work on github as the headers there also do not have ids

**Comment by edoreld** [comment]
I've been having the same problem myself

I have this: 
* [How to connect](#howtoconnect)

and this:
<h2 id="howtoconnect">How to connect</h2>

Clicking on How to connect should take me to the h2, but if I do a preview with github markdown selected it won't work. On checking the source code I can see the the id has been changed to "user-content-howtoconnect" so obviously the anchor can't work at all!

I have tried with the default and github parser & with github_inject_header_ids set to true and false, but it's still doing the same thing.

**Comment by facelessuser** [comment]
Github for some reason has started to return header ids with the `user-content` nonsense appended to ids.  I think this must be some way to namespace the content ids from the parent content you would be injected the markdown into?  I don't know why they would do it this way, but that is exactly what they return; they didn't used to.

We don't alter the original id because it used to not be there.  We actually generated the anchor ids from the header text because that was all that was available.  So github has changed things again in a non-intuitive way.

What should be done now is we should:

- read the the id github is now returning
- strip off the ridiculous `user-content` stuff
- write that back as the actual id
- and then use that newly created id to inject anchors
