### ISSUE TITLE
Sublime temporarily freezing when Github previewing

### ISSUE THREAD

**Issue by mateusazis** [revolunet/sublimetext-markdown-preview#240]
When I choose "GitHub preview", Sublime freezes for a few seconds before the preview construction is shown. You should probably load the preview in a thread different from the main one to avoid this.

**Comment by facelessuser** [comment]
As mentioned if someone is willing to do a pull request, it may be accepted, but at this point, it appears no one will be looking into this at the present.  I personally don't see a problem with a few seconds pause.

**Comment by facelessuser** [comment]
I agree that auto reload should be false out of the box.

**Comment by Aldaviva** [comment]
Hello,

This change of setting the default `enable_autoreload` value to `false` has caused LiveReload to stop working with my Markdown files. Can this be documented as a prerequisite for LiveReload to work, especially since PackageControl automatically upgrades users to get this change and the defaults no longer work? Currently the only documented requirement is having the LiveReload plugin installed.

Thank you.

**Comment by revolunet** [comment]
Hi @Aldaviva, sorry for the inconvenience. Ive updated the readme here : https://github.com/revolunet/sublimetext-markdown-preview/pull/390 is it clear enough ?

**Comment by Aldaviva** [comment]
@revolunet no worries, thanks for working on this. The readme changes look good to me. :+1:
