### ISSUE TITLE
Markdown inserts a <br> after only one \n in the original text

### ISSUE THREAD

**Issue by BruceBerry** [revolunet/sublimetext-markdown-preview#272]
I've noticed that if I write

    hello
    world

in an md file I get back

    <p>hello<br>
    world</p>

Shouldn't the `<br>` be omitted by default? This makes it difficult to use plain text word wrapping. I thought markdown ignored single "\n" characters exactly for that reason.

**Comment by facelessuser** [comment]
I don't know what configuration you are using.  If you are using Github's, then it will auto insert `<br>` tags.  If you are using Python Markdowns version, then you will also get the same because by default it includes a number of extensions that give a Github feel.  People seem to like that out of the box, but obviously not everyone will, so you are welcome to change which extensions get included by default for the Python Markdown implementation.

**Comment by PaleNeutron** [comment]
This feature annoy me a lot too.

But you can ignore it by custom settings. Here is my setting:
```
{"enabled_extensions": ["extra", "magiclink", "delete","tasklist","githubemoji", "headeranchor", "superfences", "toc", "headerid", "meta", "sane_lists", "smarty", "wikilinks"]  // nl2br is removed}
```
Hope this solve your problem.

**Comment by facelessuser** [comment]
Looks like you have a solution, so I am closing this issue.
