### ISSUE TITLE
Mathjax really sucks

### ISSUE THREAD

**Issue by DeveloperZhou** [revolunet/sublimetext-markdown-preview#298]
Everything is good but rendering the mathjax

*　sometimes it just　LIKE THIS

$$JAX1$$B$$JAX2$$
The engine thinks B is mathjax.A really Bug annoying me much.
So please fix it.Thank you.

All Best

**Comment by facelessuser** [comment]
1.  Markdown Preview does not develop Mathjax.

2.  Is your problem that Mathjax doesn't parse it proper?  Or is it that Markdown Preview doesn't send the right info to Mathjax?

If the problem is directly with Mathjax, then you will have to take the issue up with them, but I tried out your example and I see nothing wrong.  This makes me think it isn't a Mathjax problem.

```
This is a test

$$JAX1$$B$$JAX2$$

Looks fine to me.
```

![screenshot - 9_25_2015 12_42_55 pm](https://cloud.githubusercontent.com/assets/1055125/10109274/3584f424-6383-11e5-9861-db36d5ed3656.png)

You will need to provide a reproducible example, and provide your current settings since it looks to be working  from what I tired.  More than likely you have some bad formatting in your file which causing the math to not get processed correctly.

**Comment by DeveloperZhou** [comment]
Sorry for not providing more details. 

1. The first issue just like this

>绝热过程
>$$k_{A\gamma }= \frac{ dp }{ dV } |_{ A }=-\gamma \frac{ p_{ A }}{V_{A}}$$

>等温过程 
>$$k_{AT}= \frac{ dp }{ dV } |_{ A }=- \frac{ p_{ A } }{ V_{ A } }$$

* In my preview:
![image](https://cloud.githubusercontent.com/assets/13814626/10114349/0e5fb010-6422-11e5-9a33-401ea96aae58.png)

* I tried this in a independent file.And also in another two web editor.[Stackedit And MarkFeiXiang]
![In stackeidt](https://cloud.githubusercontent.com/assets/13814626/10114337/f4fe7dfe-6421-11e5-928e-48764e0c30c4.png)

2.The second issue is about sheets

----

|过程|$\Delta E$ | $Q$|A|
| -------| --------| ------ | ------|
|等容|$\Delta E=\frac{ m }{ M } C_{ v }\Delta T$ | $Q_v=\frac{ m }{ M } C_{ v }\Delta T$ | $0 $|
|等压|$\Delta E=\frac{ m }{ M } C_{ v }\Delta T$ | $Q_p=\frac{ m }{ M } C_{ v }\Delta T$ | $A_p=p(V_2-V_1)$|
|等温|$\Delta E=0$ | $Q_{ T }=\frac{ m }{ M } RT\ln { \frac{ V_2 }{ V_1 }  } $ | $A_{ T }=\frac{ m }{ M } RT\ln { \frac{ V_{ 2 } }{ V_{ 1 } }  } $|
|绝热|$\frac{ m }{ M } C_V\Delta T$ | $0$ | $\frac{ 1 }{ \gamma -1 } (p_1V_1-p_2V_2)=-\frac{ m }{ M } C_V\Delta T$|
注: $C_v=\frac{ i }{ 2 } R \quad \quad C_p=C_v+R\quad \quad \gamma =\frac{ C_p }{ C_v } =1+\frac{ 2 }{ i } $
 
----

**Comment by facelessuser** [comment]
> The first issue just like this

Did you enable this?

```js
    /*
        Enable or not mathjax support.
    */
    "enable_mathjax": false,
```

I don't seem to have an issue with this like you show in `1`.  Maybe you just don't have the feature enabled.

> 2.The second issue is about sheets

Yes, Markdown preview actually needs to preserve the mathjax content as it passes through the Python Markdown parser instead of hoping it makes it through unaltered.  The person who implemented Markdown Preview's mathjax implementation just applys mathjax to whatever _happens_ to make it through, so it doesn't surprise me that some of it doesn't get rendered right.

Because of this less than ideal implementation (and other reasons), I don't always use Markdown Preview, but I have created my own implementation where I use my own custom extensions, one of which implements [mathjax](http://facelessuser.github.io/PyMdown/extensions/math/).  I have not included my extension here because I didn't want to break backwards compatibility for the existing solution (I just help out here sometimes, Markdown Preview is not my plugin :smile:), but maybe I should consider adding it here.

> 3.The third thing is about $$JAX1$$B$$JAX2$$

I think this is related to `1`.

> 4.The last is about the refreshing

Markdown Preview needs the Sublime [LiveReload](https://github.com/dz0ny/LiveReload-sublimetext2) plugin to be set up proper for auto reload. Not sure if you have set that up.

**Comment by DeveloperZhou** [comment]
First of all, it seems I have found the reason for it.
And of course I write
```
"enable_mathjax": true;
```

I upload Sublime(and his plugins) to onedrive so that I can use it everywhere.
But something configuration in the `Appdata` I didnt copy.
[I usually use my Tablet outside and my Laptop in my dorm]

Several issues comes up, but i reload in my laptop to check. Just fine.
I blame 'preview' wrongly. Sorry for it.

----

I have visited your website about parser.Very nice. And programming is really cool, doesnt it?

Thanks for helping me solve problems.[I have been trapped for some time]
