### ISSUE TITLE
TOC extension is not working in github preview

### ISSUE THREAD

**Issue by yahyaerturan** [revolunet/sublimetext-markdown-preview#322]
When I select the Preview option, it asks me "github" or "markdown". When I select "markdown" I can see Table of Contents created. But when I select "github", It just writes `[TOC]` at the beginning of document. It does not render..

**Comment by facelessuser** [comment]
This is because the Github Flavored Markdown does not support `[TOC]`.  The "markdown" parser is done with Python Markdown and has an extension that handles "table of contents".  "github" is sent to github via their API, and they parse and return the rendered markdown; we have no control over "github".

**Comment by yahyaerturan** [comment]
@facelessuser Noted thank you. I liked "github" extension because it highlights code blocks automatically. Thanks.
