### ISSUE TITLE
Pygments style 'github' missing

### ISSUE THREAD

**Issue by eugenesvk** [revolunet/sublimetext-markdown-preview#323]
I installed the addon and followed setup instructions to get GFM markdown on OS X 10.11.3 and ST3 b3103, but realized that two things were very different from what I get when I use github parser (it took me a long while to find out how to feed a GitHub API token from the environment into ST3 and this addon, but that's another story).

**1) Wider pages with GitHub parser**
When parsing via GitHub, I get wider page (`body { width: 980px;`) vs the default parser (`body { width: 45em;`).
How do I make it consistent (I'd like to replicate GitHub locally for when I don't have internet connection).

**2) Different code color styles**
Despite what the guide says, setting `pygments_style=github` renders different colors from GitHub parser.
What's interesting is that `github` style is not showing in the list of styles (from ST3 console):
```python
>>> from pygments.styles import STYLE_MAP
>>> STYLE_MAP.keys()
dict_keys(['friendly', 'lovelace', 'paraiso-dark', 'emacs', 'vs', 'monokai', 'native', 'xcode', 'trac', 'igor', 'algol_nu', 'paraiso-light', 'pastie', 'rrt', 'default', 'colorful', 'perldoc', 'manni', 'bw', 'autumn', 'tango', 'vim', 'fruity', 'algol', 'murphy', 'borland'])
```
Same question — how do I make local markdown build consistent with GitHub?

Thanks!

P.S.
Some of my addon settings
```
"enabled_extensions": ["extra", "github", "toc", "meta", "sane_lists", "smarty", "wikilinks", "codehilite(guess_lang=True,pygments_style=github)" ]
"github_mode": "GFM"
```

**Comment by facelessuser** [comment]
> When parsing via GitHub, I get wider page (body { width: 980px;) vs the default parser (body { width: 45em;).
How do I make it consistent (I'd like to replicate GitHub locally for when I don't have internet connection).

You make it consistent by issuing a pull request.  The CSS that is used for the actual online github parser is updated occasionally (via pull request) from another repo dedicated to stripping out Github's CSS into a single file.

The local (Python Markdown) parser has a separate CSS that people don't often update.  It is slightly different as the HTML and such is slightly different due to it being a different parser.

You could also maintain your own and use it instead of the one provided.

> Despite what the guide says, setting pygments_style=github renders different colors from GitHub parser.

That is correct.  I added that theme back when Github was using Pygments as their syntax highlighter.  Then Github started using their own Textmate/Sublime compatible syntax highlighter (the same one that I think they use for Atom).  Hence the Pygments color scheme can no longer match Githubs.  Not to mention Github is always tweaking things; they can't seem to just leave their styles alone.

> What's interesting is that github style is not showing in the list of styles (from ST3 console):

When Markdown Preview was directly including Pygments, we had control over it and could natively inlcude the github themes, but now we use a dependency to include Pygments (for easier maintenance of the plugin).  Since Pygments includes their color themes via entry points, this is more difficult to include in a native way via an external python file in a Sublime plugin environment, so we have a wrapper that specially injects the old Github generated pygments CSS that allows it to seem native like but it is not.

> Same question — how do I make local markdown build consistent with GitHub?

You can't, but you can get a github feel.  Python Markdown is not the github parser, and I while I added a few extensions to give a github feel, it is not 1:1.  A matter of fact, Github just changed stuff again recently.  It used to be that you needed the nl2br extension (which is included via the github extension), but now github no longer turns new lines to br tags, so nl2br should no longer be included automatically with the github extension.

The only reason it is configured by default in a "github" feel mode is that lots of people like that.  I almost kind of feel like it shouldn't be because people get the wrong idea that it is supposed to be a github 1:1 feel.

**Comment by eugenesvk** [comment]
Ok, thanks for detailed clarifications! Maybe to avoid confusion call the option **github-feel** or something? Or just add a comment in default settings that it's not an exact replica. Then one wouldn't have an outright expectation of a 1:1 match.
