### ISSUE TITLE
Wayback Machine Links interpreted as 2 Links

### ISSUE THREAD

**Issue by tajmone** [revolunet/sublimetext-markdown-preview#395]
I've pasted in a markdown doc the following link to a website archived on WaybackMachine:

```markdown
- [WaybackMachine :: www.algonet.se/~guld1/](https://web.archive.org/web/*/http://www.algonet.se/~guld1/freefont.htm) (not archived)
```
... and the result I got in the html preview are two separate links. Here is the raw html taken from the preview document:

``` html
<ul>
<li><a href="https://web.archive.org/web/*/http://www.algonet.se/~guld1/freefont.htm">WaybackMachine :: </a><a href="http://www.algonet.se/~guld1/"></a><a href="http://www.algonet.se/~guld1/">www.algonet.se/~guld1/</a> (not archived)</li>
</ul>
``` 

... and here is the html result (I've pasted here the same raw html as above, else GitHub will parse correctly the link as a single link, and I wanted to show the problem):

<ul>
<li><a href="https://web.archive.org/web/*/http://www.algonet.se/~guld1/freefont.htm">WaybackMachine :: </a><a href="http://www.algonet.se/~guld1/"></a><a href="http://www.algonet.se/~guld1/">www.algonet.se/~guld1/</a> (not archived)</li>
</ul>

Note that the first one is actually the correct full link to WaybackMachine, the second link points to the sub-url of the original website inside the full url.

The same line of markdown, pasted here, produces the following (correct) preview:

- [WaybackMachine :: www.algonet.se/~guld1/](https://web.archive.org/web/*/http://www.algonet.se/~guld1/freefont.htm) (not archived)

SublimeText markdown-preview seems to caputre that single url twice: first in it's interity, and then only its sub-url therein contained.

I'm not sure how often similar edge-cases pop-up, but Wayback Machine is definitely a good example since it's a widespread service and will always have URLs containing nested URLs.

**Comment by facelessuser** [comment]
This is probably related to the fact that you have pymdownx.magiclink extension enabled...on the current branch, it is just known as magiclink as it has been ported in.  Basically, the link in a link isn't the issue.  The link in the Markdown link content `WaybackMachine :: www.algonet.se/~guld1/` is the problem and is getting auto linked.

[pymdown-extensions](https://github.com/facelessuser/pymdown-extensions) is actually maintained by me.  This is not a use case I planned for.  I'd have to think about a way to approach this.  You can currently disable magiclink if this is a serious problem for you.

You should open this issue upstream at pymdown-extensions to get this fixed.  I may forget without an issue there.

**Comment by tajmone** [comment]
Not a major issue at all (after all it's just showing up in preview docs), and an edge case anyway.

I just thought worth of mentioning it here when I noticed the different output in the preview and on GitHub or via pandoc — for the sake of completeness.

I'm not acquainted with the pymdown-extensions you mentioned. My gues is that if it's being used in real markdown parsing scenarios (ie: not just for preview purposes, like here), then there might be implications in the final output. I'd say that all that falls within the `( .. )` part of a markdown link shouldn't be further parsed for autolinks (unexpected results might ensue).

But as I said, not bein a user of the extensions you mentioned I'm not in a position to say much.

**Comment by facelessuser** [comment]
> I'd say that all that falls within the ( .. ) part of a markdown link shouldn't be further parsed for autolinks (unexpected results might ensue).

That's not how it's working.  That doesn't get parsed.  As I mentioned earlier, you are including a link in the `[...]` part.  That is getting auto-linked.  Normal links are run first.  *Afterwards*, MagicLink is run.  Python Markdown will parse content in inline code (like anchor links) if they are not formatted in a way to prevent it.  This is so you can get bold and italic and other styles in your displayed link.

In order for MagicLink to handle this, it would have to handle both normal and autolinked links so it could be aware of what is going on.  This is due to Python Markdown's serialization of these patterns. GFM actually does this different.  It is possible I could get creative and find another way, but we'll have to see.

There is an assumption that pymdown-extensions purpose is to provide 1:1 feature parity with GFM, but this is not actually true.  Some of the extensions in pymdown-extensions are inspired by GFM, but there is no goal to make their behavior exactly like GFM.  We sort of create a GitHub-ish feature set with them here to pacify people who wish for an offline GFM parser , but it is not GFM.  To get actual GFM, you need to use to use the GitHub parser (which can be configured in the settings file) instead of the Markdown parser (Python Markdown) (remember to specify your GitHub token).

I'm going to close this issue for the following reasons:

1. The next version of Markdown Preview will be sourcing MagicLink from the pymdown-extensions dependency and will no longer vendor the internal one making the request here no longer applicable to this repository, but making it purely a pymdown-extensions issue.  So this issue should really be filed there.

2. Technically there is no issue with MagicLink as it is behaving as expected and turning raw text links into links, even if they are nested as the plain text content of another link. It is not parsing content in `(...)` which would be a bug. So this is really a feature request to behave more like GFM does.  This is something that would need to be investigated in pymdown-extensions, not here.

**Comment by facelessuser** [comment]
A solution for this is being tracked her for MagicLink: https://github.com/facelessuser/pymdown-extensions/issues/151.  A solution is in the works in Python Markdown.  Not sure when it will make it to a release, but this will hopefully be addressed sometime in the future.
