### ISSUE TITLE
Double pipe in a code span into an array

### ISSUE THREAD

**Issue by EtienneR** [revolunet/sublimetext-markdown-preview#397]
Hello,

When I write a double pipe in a code span into an array, I have an error into the HTML file.

```
| Operator | Description |
| -------- | ----------- |
| `&&`     | And         |
| `||`     | Or          |
| `!`      | Not         |
```

The second line is broken :(

Thx for your work ;)

**Comment by facelessuser** [comment]
This is a Github Flavored Markdown error.  Since that is the parser you are using, that is why you are getting the error.  You'll see that below I'll post the table code in this comment.  Since these comments use Github Flavored Markdown, you'll see that it is broken:

| Operator | Description |
| -------- | ----------- |
| `&&`     | And         |
| `||`     | Or          |
| `!`      | Not         |

If you use the Python Markdown parser (`markdown`) instead of the GitHub Flavored Markdown (`github`), you'll see the issue goes away.

I would file this issue on GitHub's markdown parsing repo.  There is nothing we can do in this plugin as the `github` parser uses GitHub's public API, and that is what is broken.

**Comment by facelessuser** [comment]
I'm going to close this as there appears to be no actionable item to be done here.
