### ISSUE TITLE
Not working in sublime 3

### ISSUE THREAD

**Issue by tonykor** [revolunet/sublimetext-markdown-preview#416]
Hello, not working for me in sublime 3, macosx High Sierra

**Comment by facelessuser** [comment]
I'm afraid this issue is extremely vague.  If you care to elaborate more on what you did, what errors you are seeing in your console and what behavior you are seeing, someone might be able to help.

**Comment by davemulford** [comment]
I have this same issue, but on Fedora 27. I'm installing manually.

Here is my sublime-text-3 console after reloading: https://gist.github.com/davemulford/01e3f67b5c3ea39322611c38c84c8315

I've made sure the downloaded package is a valid zip file and is in the correct location:

    $ pwd
    /home/dmulford/.config/sublime-text-3/Installed Packages

    $ ls -l
    total 2000
    -rw-rw-r--. 1 dmulford dmulford 2046375 Feb 26 15:55 'Markdown Preview.sublime-package'

It's like Sublime Text isn't noticing the file?

**Comment by sunlee-newyork** [comment]
It's also not working for me - on Sublime Text 3, MacOS High Sierra. Fresh installed through Package Control.

When I run Markdown Preview and select the `github` option, a new window opens in Chrome (my default browser) but no URL populates in the nav bar and no markdown is displayed.

**Comment by facelessuser** [comment]
@davemulford, please use Package Control.  Is there a reason you are trying to install manually?  This won't pick up dependencies this way.  There is an overly elaborate way to install dependencies manually, but before I go into that, I'd suggest you just use Package Control.

@sunlee-newyork, if you have any errors in the Sublime console, it may help if you could post those here.  I'm not having issues using `github`.

Is it possible you maxed out your number of requests to the GitHub API because you haven't provided an oauth token in your settings file?

**Comment by facelessuser** [comment]
Unfortunately, no one is actually opening up dialog about their issue. I cannot solve issues by simply guessing. So if their is going to be no discussion, I'm going to have to close this issue.

**Comment by tonykor** [comment]
I have tried to reinstall the plugin and it's working now. Sorry for disturb.

**Comment by facelessuser** [comment]
No worries, I'll close this issue.

To anyone who is still having issues that they'd like resolved, please open a new issue giving detailed description of your problem so we can help you troubleshoot.  Unfortunately, vague descriptions of issues probably wont get any attention.
